package com.dtelco.app

/* Baked in, not fetched, for the same reason js/config.js is: a fetched config is one more network
 * call between the person opening the app and the first page view, and the first page view is what
 * makes every later row findable.
 *
 * Every value supplied at setup is empty below, and the app runs anyway. That is deliberate. The screens get
 * built and checked now rather than after the account arrives, and each one says on its face which
 * half of it is live.
 */
object Config {
  const val SLUG = "dtelco"
  const val BRAND = "D·TELCO"

  /* Supplied at setup: the integration key generated by the panel when the Android
     application is defined. reference/new-android-sdk- calls it a hash string containing
     application details. Without it Dengage.init is not called at all. */
  const val FIREBASE_INTEGRATION_KEY = ""

  /* The custom Data Space table, the same one the web writes. It must exist in the account before
     a single row stores; a row sent to a table that does not exist is accepted and dropped. */
  const val EVENT_TABLE = "dtelco_events"

  const val COUNTRY = "AZ"
  const val CURRENCY = "USD"
  const val CURRENCY_SYMBOL = "$"

  /* The same public, validated, rate capped functions the web storefront uses. One backend, two
     surfaces, so a recommendation the web showed is the recommendation the app shows. */
  const val FUNCTIONS = "https://raextqlludkagdntyzwn.supabase.co/functions/v1/"
  const val FEED = FUNCTIONS + "dtelco-product-feed"
  const val PROFILE = FUNCTIONS + "dtelco-profile"
  const val MESSAGE = FUNCTIONS + "dtelco-message"
  const val RELAY = FUNCTIONS + "dtelco-lead-relay"

  /* The notification channel the SDK would otherwise call "General". A person who long presses a
     notification sees this name, so it is the brand rather than a default. */
  const val NOTIFICATION_CHANNEL = "D·TELCO"

  /* Every figure this demonstration shows that no operator published is a plausible demo figure,
     and it is marked as one wherever it appears. */
  const val DEMO_NOTICE =
    "D·TELCO is a demonstration. Prices are in US dollars and every figure nobody published " +
    "is demo data."
}
